version: '3'

services:

  api:
    container_name: ai_chat_fast_api
    restart: always
    build: ./api
    volumes: ['./api:/api']
    networks:
      - apinetwork
    expose:
      - "8000"
    ports:
      - "8888:8000"

networks:
  apinetwork: